apiVersion: v1
kind: Service
metadata:
  name: countermonitor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: counterservice
  type: ClusterIP
status:
  loadBalancer: {}
