replicaCount: 1
image:
  repository: yoni101087/counterservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9083


ingress:
  enabled: true
  annotations: {}

argocdApplication:
  name: counterservice
  project: default
  source:
    repoURL: https://github.com/yoni101087/counterservice.git
    targetRevision: master
    path: ./charts
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
