name: Manual deploy

on:
  workflow_dispatch:


#name: Kubernetes Deployment Workflow

#on:
#  push:
#    branches:
#      - master

jobs:

  deploy-app:
    runs-on: self-hosted   # Specify the runner label for your self-hosted runner
    steps:

      - name: Get short SHA
        id: short_sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short=7 $GITHUB_SHA)"

      - name: Log in to ArgoCD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: argocd login $ARGOCD_SERVER --insecure --username admin --password $ARGOCD_TOKEN

      - name: Check if Repo Exists in ArgoCD
        id: check-argocd-repo
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        run: |
          ARGOCD_TOKEN=${{ secrets.ARGOCD_TOKEN }}
          REPO_NAME="yoni101087/counterservice"  # Replace with the repo you want to check

          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $ARGOCD_TOKEN" "$ARGOCD_SERVER/api/v1/applications/$REPO_NAME")
          if [ $response -eq 200 ]; then
            echo "Repo $REPO_NAME exists in ArgoCD"
          else
            echo "Repo $REPO_NAME does not exist in ArgoCD"
            exit 1
          fi

      - name: Add Repository to ArgoCD
        if: failure() # Skip if repo exists
        env:
          REPO_URL: git@github.com:yoni101087/counterservice.git
        run: |
          argocd repo add $REPO_URL \
            --name counterservice \
            --insecure-ignore-host-key \
            --ssh-private-key-path ~/.ssh/id_rsa
            

      - name: Deploy Application using ArgoCD
        env:
          REPO_PATH: ./charts  # Change this to your application's path
          APP_NAMESPACE: default
          IMAGE_TAG: latest  # You can set this to your desired tag
        run: |
          argocd app create counterservice \
            --repo https://github.com/yoni101087/CounterService.git \
            --path $REPO_PATH \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace default \
            --revision master  # Change this to your desired branch or revision

#          argocd app set counterservice \
#            --values image.tag=$IMAGE_TAG

      - name: Trigger Synchronization
        run: |
          argocd app sync counterservice

  test-app:
    needs: deploy-app
    runs-on: self-hosted   # Specify the runner label for your self-hosted runner
    steps:
      - name: Check out code
        uses: actions/checkout@v3



  save-artifact-as-stable:
    needs: test-app
    runs-on: self-hosted
    steps:
      - name: Package Helm chart
        run: |
          helm package ./charts

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-release-${{ steps.short_sha.outputs.short_sha }}
          path: ./counterservice-0.1.0.tgz
          


      - name: Upload artifact to Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: 'http://nexus.yonif.net'  # Replace with your Nexus URL
          NEXUS_REPOSITORY: 'counterservice'  # Replace with the repository ID in Nexus
        run: |
          curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file ./counterservice-0.1.0.tgz $NEXUS_URL/repository/$NEXUS_REPOSITORY/my-release/${{ steps.short_sha.outputs.short_sha }}/my-release-${{ steps.short_sha.outputs.short_sha }}-stable.tgz

